# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200422_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default='', max_length=254),
        ),
    ]
