# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200422_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
